import Head from "next/head";
import { Box, Typography } from "@mui/material";

import API from "@/api";
import { useState } from "react";
import { Form } from "@/components";

export default function Home() {
  const [messages, setMessages] = useState(["Hi", "Bye", "Now"]);

  const predict = async (callback) => {
    setMessages([...messages, callback.question]);

    try {
      const { data } = await API.post("predict", callback);

      setMessages([...messages, , data.answer]);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>QandAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          w: "100%",
          my: 2,
        }}
      >
        {messages.map((message, index) => {
          return (
            <Box
              key={`Mes-${index}`}
              sx={{
                backgroundColor: index % 2 === 0 ? "#222" : "#333",
                p: 2,
              }}
            >
              <Typography
                color={index % 2 === 0 ? "primary" : "info.main"}
                variant="h6"
                gutterBottom
              >
                {index % 2 === 0 ? "User" : "AI"}
              </Typography>
              <Typography variant="body1">{message}</Typography>
            </Box>
          );
        })}
        <br />
        <br />
        <Box
          sx={{
            height: "100%",
            display: "flex",
            bottom: 0,
          }}
        >
          <Form
            name="predict"
            btnStyle={{ color: "primary" }}
            callback={predict}
          />
        </Box>
      </Box>
    </>
  );
}
