import Head from "next/head";
import { Box, Container, Typography } from "@mui/material";

import API from "@/api";
import { useState } from "react";
import { Form } from "@/components";

export default function Home() {
  const [messages, setMessages] = useState([
    "Hi",
    "Bye",
    "Now",
    "Hi",
    "Bye",
    "Now",
    "Hi",
    "Bye",
    "Now",
    "Kirrrrrrrrrrrrrrrrrrr",
  ]);

  const predict = async (callback) => {
    setMessages([...messages, callback.question]);

    try {
      const { data } = await API.post("predict", callback);

      setMessages([...messages, , data.answer]);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>QandAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          w: "100%",
          mb: "6rem",
        }}
      >
        {messages.map((message, index) => {
          return (
            <Box
              key={`Mes-${index}`}
              sx={{
                backgroundColor: index % 2 === 0 ? "#333" : "#222",
                p: 2,
              }}
            >
              <Container>
                <Box sx={{ mx: "1rem" }}>
                  <Typography
                    color={index % 2 === 0 ? "primary" : "info.main"}
                    variant="h6"
                    gutterBottom
                  >
                    {index % 2 === 0 ? "You" : "AI"}
                  </Typography>
                  <Typography variant="body1">{message}</Typography>
                </Box>
              </Container>
            </Box>
          );
        })}
        <Box
          sx={{
            position: "fixed",
            bottom: 0,
            left: 0,
            right: 0,
            background: "linear-gradient(to top, #222, #333)",
          }}
        >
          <Container
            sx={{
              my: "1rem",
            }}
          >
            <Form
              name="predict"
              btnStyle={{ color: "primary" }}
              callback={predict}
            />
          </Container>
        </Box>
      </Box>
    </>
  );
}
